<?php
require_once('tcpdf/tcpdf.php');

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Project Author');
$pdf->SetTitle('Project Title');
$pdf->SetSubject('Project Subject');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// Set default header data
$pdf->SetHeaderData('', 0, 'Project Title', 'Generated by TCPDF');
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(15, 27, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set font
$pdf->SetFont('dejavusans', '', 12);

// Add a page
$pdf->AddPage();

// Cover Page
$pdf->SetFont('dejavusans', 'B', 20);
$pdf->Cell(0, 10, 'Project Title', 0, 1, 'C');
$pdf->Ln(10);
$pdf->SetFont('dejavusans', '', 12);
$pdf->Cell(0, 10, 'Cover page detailing all important aspects of the project.', 0, 1, 'C');
$pdf->AddPage();

// Table of Contents
$pdf->SetFont('dejavusans', 'B', 16);
$pdf->Cell(0, 10, 'Table of Contents', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "1. Project Overview
2. Technology Stack
3. Features
4. Screenshots
5. Challenges and Solutions
6. Future Improvements
7. Source Code Links
");
$pdf->AddPage();

// Project Overview
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Project Overview', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, 'This section provides an overview of the project, its purpose, and features.');
$pdf->AddPage();

// Technology Stack
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Technology Stack', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "- HTML: Structure of the web pages
- CSS: Styling the web pages
- JavaScript: Client-side scripting
- PHP: Server-side processing");
$pdf->AddPage();

// Features List
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Features', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "1. Responsive Design
2. User Authentication
3. Real-time Data Processing
4. Customizable Reports
");
$pdf->AddPage();

// Screenshots
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Screenshots', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "Screenshot 1: Description of what the screenshot shows.
Screenshot 2: Description of what the screenshot shows.
");
$pdf->AddPage();

// Challenges and Solutions
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Challenges and Solutions', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "- Challenge 1: Solution to challenge 1
- Challenge 2: Solution to challenge 2
");
$pdf->AddPage();

// Future Improvements
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Future Improvements', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "1. Additional features to enhance user experience
2. Better error handling and performance enhancements
");
$pdf->AddPage();

// Source Code Links
$pdf->SetFont('dejavusans', 'B', 14);
$pdf->Cell(0, 10, 'Source Code Links', 0, 1);
$pdf->SetFont('dejavusans', '', 12);
$pdf->MultiCell(0, 10, "- GitHub Repository: [insert link]
- Documentation: [insert link]
");
$pdf->AddPage();

// Footer
$pdf->SetY(-15);
$pdf->SetFont('dejavusans', 'I', 8);
$pdf->Cell(0, 10, 'Page '.$pdf->getAliasNumPage().' of '.$pdf->getAliasNbPages().' - '.date('Y-m-d H:i:s'), 0, 0, 'C');

// Output PDF
$pdf->Output('project_report.pdf', 'I');
?>